### ISSUE TITLE
Bot crashes after accepting correspondence game

### ISSUE THREAD

**Issue by tomeckip** [careless25/lichess-bot#112]
Accept Correspondence casual challenge from tomecki(1312)
--- Process Queue. Total Queued: 1. Total Used: 0
--- Process Used. Total Queued: 0. Total Used: 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): lichess.org
DEBUG:urllib3.connectionpool:https://lichess.org:443 "GET /api/bot/game/stream/AI9yTarp HTTP/1.1" 200 None
ERROR:backoff:Backing off play_game(...) for 0.5s (AttributeError: 'NoneType' object has no attribute 'get')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): lichess.org
DEBUG:urllib3.connectionpool:https://lichess.org:443 "GET /api/bot/game/stream/AI9yTarp HTTP/1.1" 200 None
ERROR:backoff:Backing off play_game(...) for 1.9s (AttributeError: 'NoneType' object has no attribute 'get')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): lichess.org
DEBUG:urllib3.connectionpool:https://lichess.org:443 "GET /api/bot/game/stream/AI9yTarp HTTP/1.1" 200 None
ERROR:backoff:Backing off play_game(...) for 1.1s (AttributeError: 'NoneType' object has no attribute 'get')

And so on....
The result is the same when starting a correspondence game with any time control including unlimited.

**Comment by ornicar** [comment]
lichess-bot doesn't support correspondence games.

**Comment by ornicar** [comment]
version 1.1.0 does.
