### ISSUE TITLE
Lichess-bot does not work when opened as pipe

### ISSUE THREAD

**Issue by smartchessguiapp** [careless25/lichess-bot#114]
Of course you can say: "Idiot! No one ever told you that you can use lichess-bot as a piped process. Use it the normal way, at the console type `python lichess-bot.py`. Lol."

I really need help. I want to use lichess-bot from a web server and I want the server to be able to communicate with the bot through stdin/stdout. I don't understand what is going on.

When I open it with `subprocess.Popen`, these lines do nothing ( no error is reported, just they do nothing ):

https://github.com/careless25/lichess-bot/blob/master/lichess-bot.py#L52

https://github.com/careless25/lichess-bot/blob/master/lichess-bot.py#L82

If instead of these processes I create threads, the bot works.

It seems that `multiprocessing` module does not work as expected in a piped process. I don't understand what is going on. Please help!

**Comment by ddugovic** [comment]
Dumb question... does `python -u lichess-bot.py` work?

**Comment by careless25** [comment]
@ddugovic no that means that you are passing the u flag to Python rather than passing it to lichess-bot.py

**Comment by ddugovic** [comment]
Right, but given that he's trying to use unbuffered stdout isn't that the goal?
