### ISSUE TITLE
resign of opponent gives confusing error

### ISSUE THREAD

**Issue by flok99** [careless25/lichess-bot#126]
The confusing part here is the "Abandoning game due to connection error".

Welcome embla!
You're now connected to https://lichess.org/ and awaiting challenges.
Something went wrong. Game is starting and we don't have a queued process
--- Process Used. Total Queued: 0. Total Used: 1
+++ https://lichess.org/LYK1CWvK/white Rapid vs flok99(1268?)
Got move e2e4 from book engines/book.bin
Got move g1f3 from book engines/book.bin
Got move d2d4 from book engines/book.bin
Got move d4e5 from book engines/book.bin
--- https://lichess.org/LYK1CWvK/white Game over
+++ Process Free. Total Queued: 0. Total Used: 0
    Accept Rapid rated challenge from flok99(1263)
--- Process Queue. Total Queued: 1. Total Used: 0
--- Process Used. Total Queued: 0. Total Used: 1
+++ https://lichess.org/PzpKijIv/black Rapid vs flok99(1263?)
Got move e7e5 from book engines/book.bin
Got move g8f6 from book engines/book.bin
Got move c7c6 from book engines/book.bin
ERROR:backoff:Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/PzpKijIv/move/b7b5)
Abandoning game due to connection error
Traceback (most recent call last):
  File "lichess-bot.py", line 151, in play_game
    li.make_move(game.id, best_move)
  File "/home/folkert/lichess-bot/lichess.py", line 71, in make_move
    return self.api_post(ENDPOINTS["move"].format(game_id, move))
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/home/folkert/lichess-bot/lichess.py", line 61, in api_post
    response.raise_for_status()
  File "/home/folkert/lichess-bot/.venv/lib/python3.4/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/PzpKijIv/move/b7b5
--- https://lichess.org/PzpKijIv/black Game over
+++ Process Free. Total Queued: 0. Total Used: 0

**Comment by gbtami** [comment]
It's a known issue. See https://github.com/careless25/lichess-bot/issues/125
