### ISSUE TITLE
problem with pyyaml 3.12 and python 3.7

### ISSUE THREAD

**Issue by tsoj** [careless25/lichess-bot#136]
I needed to change the line `PyYAML==3.12` in the `requirements.txt` to `PyYAML==3.13`, to get the command `pip install -r requirements.txt` to run successfully. Maybe related to [https://github.com/yaml/pyyaml/issues/126](url).

**Comment by careless25** [comment]
This should fix it: https://github.com/careless25/lichess-bot/pull/137
