### ISSUE TITLE
shareware engines that don´t use the WB or UCI-protocol

### ISSUE THREAD

**Issue by yellow-panther** [careless25/lichess-bot#138]
What´s about other proprietary protocols like Fritz (ChessBase) or Chess Genius Classic (Millenium Chess System) playing on Lichess?
cf. rheir websites on http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

**Comment by gbtami** [comment]
I don't think it will happen because lichess-bot is based on python-chess an python-chess doesn't support these proprietary protocols at all.

**Comment by ddugovic** [comment]
Either that, or if you could make an adapter to force those engines to communicate via CECP or UCI I suppose you could use them.

**Comment by careless25** [comment]
Closing since it won't be supported
