### ISSUE TITLE
Bot does not play

### ISSUE THREAD

**Issue by justdvl** [careless25/lichess-bot#149]
Hello, I installed the bot on my Win10 following the instructions. After I run the bot, I go to my other account and try to play with it. It accepts the challenge, game starts, but bot makes no moves. Sometimes it goes grey for few seconds ("left the game"), than back green ("joined the game"), but won't play. Console stays in this state:

> (.venv) PS C:\users\david\documents\github\lichess-bot> python lichess-bot.py -u
> 2018-11-23 18:27:28,975: .   _/|
> .  // o\
> .  || ._)  lichess-bot 1.1.0
> .  //__\
> .  )___(   Play on Lichess with a bot
> 
> 2018-11-23 18:27:29,279: Welcome justdvl_bot!
> 2018-11-23 18:27:29,279: You're now connected to https://lichess.org/ and awaiting challenges.
> 2018-11-23 18:27:30,747: --- Process Used. Total Queued: 0. Total Used: 1
> 2018-11-23 18:27:38,232:     Accept Blitz rated challenge from justdvl(1337)
> 2018-11-23 18:27:38,232: --- Process Queue. Total Queued: 1. Total Used: 1
> 2018-11-23 18:27:38,361: --- Process Used. Total Queued: 0. Total Used: 2

Thanks for help

**Comment by justdvl** [comment]
As an engine, I am using stockfish_9_x64.exe downloaded from https://stockfishchess.org

**Comment by William-Edward** [comment]
Also have this issue on windows 7. Same stockfish engine (stockfish_9_x64.exe). 

Engine is functional - I tested a uci game with it via cmd.

**Comment by careless25** [comment]
Can you both try running the bot with verbose logging: 
```
python lichess-bot.py  -v
```

**Comment by justdvl** [comment]
I can. I did quite a few print statements here and there to try to figure it out (I'm sure you know which ones are those)

`PS C:\Users\David\Documents\GitHub\lichess-bot> python lichess-bot.py -v
2018-12-04 22:44:08,188: None
2018-12-04 22:44:08,221: Starting new HTTPS connection (1): lichess.org:443
2018-12-04 22:44:08,929: https://lichess.org:443 "GET /api/account HTTP/1.1" 200 None
2018-12-04 22:44:08,930: Welcome justdvl_bot!
2018-12-04 22:44:08,930: You're now connected to https://lichess.org/ and awaiting challenges.
I start game..
Engine factory inside start: functools.partial(<function create_engine at 0x0000021D17588C80>, {'token': 'wZ58LlHqcFun8KAg', 'url': 'https://lichess.org/', 'engine': {'dir': './engines/', 'name': 'stockfish_9_x64_bmi2.exe', 'protocol': 'uci', 'polyglot': {'enabled': False, 'book': {'standard': 'engines/book.bin'}, 'max_depth': 4, 'min_weight': 1, 'selection': 'weighted_random'}, 'uci_options': {'Move Overhead': 100, 'Threads': 4, 'Hash': 256}, 'silence_stderr': False}, 'abort_time': 20, 'fake_think_time': False, 'challenge': {'concurrency': 4, 'sort_by': 'best', 'accept_bot': True, 'max_increment': 180, 'min_increment': 0, 'variants': ['standard'], 'time_controls': ['bullet', 'blitz', 'rapid'], 'modes': ['casual', 'rated']}})
event stream url:  https://lichess.org/api/stream/event
response:  <Response [200]>
event  {'type': 'ping'}
control_queue size:  0
event  {'type': 'ping'}
control_queue size:  0
event  {'type': 'ping'}
control_queue size:  0
event  {'type': 'challenge', 'challenge': {'id': 'jYXVgtfT', 'status': 'created', 'challenger': {'id': 'justdvl', 'name': 'justdvl', 'title': None, 'rating': 1520, 'online': True}, 'destUser': {'id': 'justdvl_bot', 'name': 'justdvl_bot', 'title': 'BOT', 'rating': 1500, 'provisional': True, 'online': True}, 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'rated': True, 'speed': 'rapid', 'timeControl': {'type': 'clock', 'limit': 300, 'increment': 5, 'show': '5+5'}, 'color': 'random', 'perf': {'icon': '#', 'name': 'Rapid'}}}
control_queue size:  0
2018-12-04 22:44:34,107: Resetting dropped connection: lichess.org
2018-12-04 22:44:34,953: https://lichess.org:443 "POST /api/challenge/jYXVgtfT/accept HTTP/1.1" 200 None
2018-12-04 22:44:34,954:     Accept Rapid rated challenge from justdvl(1520)
2018-12-04 22:44:34,955: --- Process Queue. Total Queued: 1. Total Used: 0
event  {'type': 'ping'}
control_queue size:  1
event  {'type': 'gameStart', 'game': {'id': 'jYXVgtfT'}}
control_queue size:  0
2018-12-04 22:44:34,958: --- Process Used. Total Queued: 0. Total Used: 1
url:  https://lichess.org/api/bot/game/stream/jYXVgtfT
response:  <Response [200]>
I play game..
play game - game  https://lichess.org/jYXVgtfT/white Rapid vs justdvl(1520)
play game - board:
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
engine path:  C:/Users/David/Documents/GitHub/lichess-bot/engines/stockfish.exe`

**Comment by gbtami** [comment]
From your debug prints it seems that your config engine name is 'name': 'stockfish_9_x64_bmi2.exe'
but the engine path printed in last line is stockfish.exe

**Comment by ddugovic** [comment]
As an aside, I'm curious whether my Multi-Variant Stockfish branch runs on Windows: https://github.com/ddugovic/lichess-bot/tree/download_github_release

**Comment by justdvl** [comment]
Sorry for confusion, I have just hard setted this path in engine wrapper for test purposes, there is not a problem, I have tried all the paths and more engines.

I am wondering if something else is not a problem. I have started a game against my bot, I got a white, so I plaied a move. But bot doesn't even receive an event that move was played, according to log:
event  {'type': 'ping'}
event  {'type': 'challenge', 'challenge': {'id': 'eDh4aD35', 'status': 'created', 'challenger': {'id': 'justdvl', 'name': 'justdvl', 'title': None, 'rating': 1331, 'online': True, 'lag': 4}, 'destUser': {'id': 'justdvl_bot', 'name': 'justdvl_bot', 'title': 'BOT', 'rating': 1500, 'provisional': True, 'online': True}, 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'rated': True, 'speed': 'blitz', 'timeControl': {'type': 'clock', 'limit': 240, 'increment': 3, 'show': '4+3'}, 'color': 'white', 'perf': {'icon': ')', 'name': 'Blitz'}}}
2018-11-26 19:54:40,785: Resetting dropped connection: lichess.org
2018-11-26 19:54:40,874: https://lichess.org:443/ "POST /api/challenge/eDh4aD35/accept HTTP/1.1" 200 None
2018-11-26 19:54:40,875:     Accept Blitz rated challenge from justdvl(1331)
2018-11-26 19:54:40,875: --- Process Queue. Total Queued: 1. Total Used: 2
event  {'type': 'gameStart', 'game': {'id': 'BBvKlrfq'}}
2018-11-26 19:54:41,014: --- Process Used. Total Queued: 0. Total Used: 3
updates <generator object Response.iter_lines at 0x000001743CEB6BF8>
game  https://lichess.org/BBvKlrfq/black Blitz vs justdvl(1331)
event  {'type': 'ping'}
event  {'type': 'ping'}
or is the move encoded in "updates" object?

**Comment by careless25** [comment]
Can you update to the latest release and try again? 
Also can you post your config here?

**Comment by William-Edward** [comment]
Gave it a try on latest release using stockfish 10

![image](https://user-images.githubusercontent.com/24722661/49737556-de050e00-fc95-11e8-87e8-3e32732d6b4e.png)

Doesn't play. Here's the config: https://pastebin.com/E5S8zzti

**Comment by justdvl** [comment]
I got a fresh new install and followed the steps again.. Still doesnt play.. Heres my console log:

> Collecting backoff==1.6.0 (from -r requirements.txt (line 8))
> Installing collected packages: certifi, chardet, idna, python-chess, PyYAML, urllib3, requests, backoff
> Successfully installed PyYAML-3.13 backoff-1.6.0 certifi-2018.10.15 chardet-3.0.4 idna-2.7 python-chess-0.23.10 requests-2.21.0 urllib3-1.24.1
> (.venv) PS C:\users\david\documents\github\lichess-bot> python lichess-bot.py -v
> 2018-12-15 10:57:45 __main__[24668] [1mINFO[0m
>     .   _/|
>     .  // o\
>     .  || ._)  lichess-bot 1.1.1
>     .  //__\
>     .  )___(   Play on Lichess with a bot
> 
> 2018-12-15 10:57:47 __main__[24668] [1mINFO[0m Welcome justdvl_bot!
> 2018-12-15 10:57:47 __main__[24668] [1mINFO[0m You're now connected to https://lichess.org/ and awaiting challenges.
> 2018-12-15 10:57:58 __main__[24668] [1mINFO[0m     Accept Rapid rated challenge from justdvl(1520)
> 2018-12-15 10:57:58 __main__[24668] [1mINFO[0m --- Process Queue. Total Queued: 1. Total Used: 0
> 2018-12-15 10:57:58 __main__[24668] [1mINFO[0m --- Process Used. Total Queued: 0. Total Used: 1
> 

here is my config.yml (I only changed token and engine path) : https://pastebin.com/qWY9E1NA

**Comment by careless25** [comment]
Can you pull https://github.com/careless25/lichess-bot/pull/162 and see if it works?

**Comment by William-Edward** [comment]
Just tried it as well. It works :+1:

**Comment by careless25** [comment]
Ok closing!
