### ISSUE TITLE
Support for Variants

### ISSUE THREAD

**Issue by HarshithBolar** [careless25/lichess-bot#25]
Set UCI option "UCI_Variant" to key obtained from "variant" field of "Game info" when setting up the engine. So the engine can automatically switch to the correct variant when a game starts.

**Comment by ddugovic** [comment]
I maintain an experimental fork where I am experimenting with this.

**Comment by ZirconiumX** [comment]
Likewise there is the xboard `variant` command.

**Comment by ddugovic** [comment]
Nevermind, I see I'm in way over my head here (I can't figure out how to access the game variant).

**Comment by ddugovic** [comment]
Oh wait, maybe f32b6cfe45eea1f08b57a4067242e4a1ce8ad731 works?

**Comment by HarshithBolar** [comment]
This is great! Works fine for all variants except Chess960 and FromPosition.

```
ValueError("unsupported variant: {0}".format(name))
ValueError: unsupported variant: Chess960
```

**Comment by ornicar** [comment]
Maybe you should make a PR, @ddugovic

**Comment by careless25** [comment]
https://github.com/careless25/lichess-bot/pull/36 should solve variants for UCI engines except fromPosition

**Comment by gbtami** [comment]
The fromPosition is fixed in https://github.com/careless25/lichess-bot/pull/52

**Comment by ddugovic** [comment]
Taking a look at `python-chess` documentation, rather than setting `UCI_Chess960` in the configuration file, it's possible to set it on a per-game basis.

**Comment by ddugovic** [comment]
Once `From Position` is enabled, maybe for standard chess the `gameState` sent by Lichess could be compressed (starting from the FEN of the last pawn move or capture)?
