### ISSUE TITLE
KeyError: 'max_concurrent_games'

### ISSUE THREAD

**Issue by tttony** [careless25/lichess-bot#26]
EDIT: sorry I didn't see this (https://github.com/careless25/lichess-bot/issues/20) closed issues, I will try it 

Python: 3.6
Windows 7 x64

Everything installed without any error

I just type: main.py and this error is showed

> Welcome SkiullOfficial!
> Process Process-2:
> Traceback (most recent call last):
>   File "C:\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
>     self.run()
>   File "C:\Python\Python36\lib\multiprocessing\process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "F:\Descargas\Compressed\lichess-bot-master\skiull-0.3\main.py", line 26,
>  in watch_control_stream
>     with logging_pool.LoggingPool(CONFIG['max_concurrent_games']+1) as pool:
> KeyError: 'max_concurrent_games'

**Comment by HarshithBolar** [comment]
CONFIG is passed as an empty dict when `watch_control_stream()` function is called, this results in a KeyError. 

```
def watch_control_stream(control_queue, li):
    with logging_pool.LoggingPool(CONFIG['max_concurrent_games']+1) as pool:
        for evnt in li.get_event_stream().iter_lines():
            if evnt:
                event = json.loads(evnt.decode('utf-8'))
                control_queue.put_nowait(event)
```
Same issue in `setup_engine()`, CONFIG is an empty dict so `CONFIG["engine"]` gives a KeyError.
```
def setup_engine(engine_path, board, weights=None, threads=None):
   ...
    global CONFIG
    if CONFIG["engine"].get("protocol") == "xboard":
        return engine_wrapper.XBoardEngine(board, commands)

    return engine_wrapper.UCIEngine(board, commands)
```

**Comment by tttony** [comment]
In this issue https://github.com/careless25/lichess-bot/issues/20, @careless25 says that only support Python3, I installed python 3.6, do I have to install Python 3.0?

@HarshithBolar did you solve the problem?

**Comment by ornicar** [comment]
You want the latest version of Python3.

**Comment by tttony** [comment]
Thanks @ornicar, as I said I have 3.6 and keeps showing that error message

To solve it I replaced: `CONFIG['max_concurrent_games']` with `1` and commented these two lines  in `main.py`:

```
#if CONFIG["engine"].get("protocol") == "xboard":
    #    return engine_wrapper.XBoardEngine(board, commands)
```

**Comment by careless25** [comment]
Pushed a fix. Confirm that its working and I will close the issue
