### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by futuristicPlayer** [careless25/lichess-bot#33]
Hi, I'm trying to set up stockfish9. I followed all the steps mentioned here, but when the game is about to start, I get this error message:
https://pastebin.com/w78Dw9mi 
Do you know why is this happening? 
Thanks in advance.

**Comment by gbtami** [comment]
Try `chmod +x your_stockfish_file`

**Comment by HarshithBolar** [comment]
It's because your Stockfish executable doesn't have execute permission. @gbtami solution will work.

**Comment by futuristicPlayer** [comment]
Oh yeah, I forgot to give it permission, thank you so much.
