### ISSUE TITLE
LeelaZero starts playing slow at the end

### ISSUE THREAD

**Issue by Aspiration-to-Stars** [careless25/lichess-bot#35]
https://lichess.org/EtBqtAug/white
It got a winning position, but then started to play slow and lost on time, although it had 2 seconds left, and could make about 20-25 moves with it's usual speed.

**Comment by HarshithBolar** [comment]
Sounds like more of a lag issue

**Comment by Aspiration-to-Stars** [comment]
No, it's not lag, it happens always at the end, and I have always good connection.

**Comment by careless25** [comment]
@Aspiration-to-Stars That is a bug with LeelaZero engine. That is out of scope for this repo.
