### ISSUE TITLE
LeelaZero only thinks on its own move, and not when it's an opponent's move

### ISSUE THREAD

**Issue by Aspiration-to-Stars** [careless25/lichess-bot#38]
When I tried CPU version. There are fluctuations in task manager from 61% (on its own move) usage to about 20% (when an opponent has to move). If it was thinking while an opponent is making a move, it would be stronger, I think.

**Comment by careless25** [comment]
@Aspiration-to-Stars These are engine specific bugs. Out of scope for this repo. 
Also, LeelaZero still doesn't have "ponder" working. So it won't be supported until they fix that. You can check their progress on `leela-chess` repo
