### ISSUE TITLE
When running stockfish 9 64bit, it only uses about 25% of CPU power

### ISSUE THREAD

**Issue by Aspiration-to-Stars** [careless25/lichess-bot#39]
Maybe it could be made to use more CPU power?

**Comment by ZirconiumX** [comment]
Do you have a quad-core CPU?

**Comment by Aspiration-to-Stars** [comment]
@ZirconiumX, yes.

**Comment by ZirconiumX** [comment]
Stockfish doesn't use GPU, and I bet you don't have something like
```yaml
ucioptions:
  - Threads: 4
```
in your `config.yml`. Stockfish is simply using all of one CPU core, not a quarter of one CPU core.

**Comment by Aspiration-to-Stars** [comment]
Thank you, now it seems better, but still I think not using full load:
https://i.snag.gy/RL8qBM.jpg
Is it ok? Maybe it's because Hash is only 1024?
