### ISSUE TITLE
Playing speed

### ISSUE THREAD

**Issue by futuristicPlayer** [careless25/lichess-bot#43]
For some reason the bot is playing very slowly, and always loses on time (by a big margin) taking way too much time even for obvious moves. What could be the cause? Does it have something to do with the option "Threads" and "hash"? Also, it's not clear to me what should I put on those fields.

**Comment by careless25** [comment]
Also what is your ping on Lichess?

**Comment by futuristicPlayer** [comment]
I'm using Ubuntu 16.04 LTS, the engine is stockfish_9_x64_popcnt.exe (I know it's the windows version, but the linux version doesn't work), on the protocol field I have "uci". My ping on lichess is somewhat between 240 ms and 320ms depending on the moment. Also, I added a book file, which should, in theory, make it play faster at least on the first moves, but it is still just as slow. On the "threads" and "hash" I'm not sure what to put (I don't know for instance if the hash number would be interpreted in MB or any other unity).

**Comment by ddugovic** [comment]
For TCEC events, the official Stockfish team set parameter `Move Overhead` to 1000 to avoid time losses.
