### ISSUE TITLE
Opening books

### ISSUE THREAD

**Issue by HarshithBolar** [careless25/lichess-bot#45]
The engine is not using opening books, is there something more you have to do other than specifying the book name in `config.yml`?

**Comment by mroh69** [comment]
which engine do you mean? (not all use polyglot books, some need several options etc...)

**Comment by HarshithBolar** [comment]
I was using stockfish. I set `BestBookMove` to `true` but still no luck. Even tried setting `Own Book` to `true` but that didn't work either.

**Comment by mroh69** [comment]
where is the book in the filesystem and what is your config?

**Comment by HarshithBolar** [comment]
The book is present in my "engines" directory. And here's a snippet of my config file:

```
ucioptions:                  
  Move Overhead: 300         
  Hash: "16384"
  Book File: "./engines/Perfect2017.bin"
  BestBookMove: true
  OwnBook: true
  Ponder: true
```

**Comment by HarshithBolar** [comment]
I was going through Lichess forums where the poster discusses about this issue.

https://lichess.org/forum/lichess-feedback/tricks-to-improve-bot-performance#9

I will have to try this later and see if it works.

**Comment by HarshithBolar** [comment]
@mroh69 

```
id name Stockfish 9 64 POPCNT
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Debug Log File type string default 
option name Contempt type spin default 20 min -100 max 100
option name Threads type spin default 1 min 1 max 512
option name Hash type spin default 16 min 1 max 131072
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 30 min 0 max 5000
option name Minimum Thinking Time type spin default 20 min 0 max 5000
option name Slow Mover type spin default 89 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 6 min 0 max 6
```

@gbtami You're right, Stockfish has no options to set an opening book.

**Comment by ddugovic** [comment]
I think `OwnBook` was removed in SF 4 because no modern engine manages its own openings.

**Comment by HarshithBolar** [comment]
You're right @ddugovic, you cannot add opening book directly to the engine. I followed the instructions in that lichess link to add a polyglot opening book to lichess-bot and it worked.

**Comment by ddugovic** [comment]
Oh wow, I'll need to read the directions and try that!

**Comment by ddugovic** [comment]
Hm, actually it seems #53 is still under development?  Or maybe it only works for some engines? idk

**Comment by gbtami** [comment]
Tested https://github.com/careless25/lichess-bot/pull/53 it with PyChessBot. It works great!

**Comment by careless25** [comment]
https://github.com/careless25/lichess-bot/pull/53 is merged in. Please re-test and report back
