### ISSUE TITLE
Create seek 

### ISSUE THREAD

**Issue by gbtami** [careless25/lichess-bot#49]
It would be a great enhancement having a new seek section in config.yml with some user defined seek lines. Using this if a BOT has a free process (and challenges queue is empty) pychess-bot automatically send a new seek (picking the next one from config.yml seek section) to be appear on lichess lobby tab.

**Comment by ornicar** [comment]
No point in having engines play when no-one is looking.

If you're looking to keep your CPU warm, please give https://github.com/niklasf/fishnet a try instead.

**Comment by ddugovic** [comment]
@gbtami To that end, how about using BOTs to study games?  It would be cool if somehow https://github.com/rpdelaney/python-chess-annotator and/or other annotators could auto-annotate studies upon command...

**Comment by gbtami** [comment]
Isn't "Analysis board -> Request a computer analysis" good enough or you are talking about some different idea?

**Comment by ddugovic** [comment]
I'm talking about using `python-chess-annotator` (or any other custom annotator) integrated with any engine(s), database(s), third-party API(s), etc. instead of requiring Lichess server-side analysis.

**Comment by gbtami** [comment]
Ah, I see now. Good idea!

**Comment by gbtami** [comment]
Just seen that CDill suggested the similar idea at https://lichess.org/forum/team-lichess-bots/bot-ratings#5
Seems a perfect solution to enhance bots visibility.

**Comment by gbtami** [comment]
Seems other BOT authors like this also. See https://lichess.org/forum/team-lichess-bots/more-active-bots

**Comment by ddugovic** [comment]
I agree, re-working the "play against the machine" feature to list all available (AI and BOT) opponents would be interesting.  But regardless of how it's presented, a change like that would require some sort of seek API so BOTs could indicate what categories of challenges they would accept.
