### ISSUE TITLE
ERROR:backoff:Backing off api_post(...)

### ISSUE THREAD

**Issue by vshcherbyna** [careless25/lichess-bot#56]
Hello,

Thanks for a great initiative on bridge between lichess and engines. This is really great!

I am running the bot on Windows using python3 and normally it works well. Sometimes, however, when bot accepts games the lichess-bot fails with the following error:

Accept UltraBullet challenge from Stockfish9-FullPower
ERROR:backoff:Backing off api_post(...) for 0.8s (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)                                                                            ERROR:backoff:Backing off api_post(...) for 1.0s (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)                                                                            ERROR:backoff:Backing off api_post(...) for 2.2s (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)                                                                            ERROR:backoff:Backing off api_post(...) for 1.8s (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)                                                                            ERROR:backoff:Backing off api_post(...) for 13.7s (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)                                                                           ERROR:backoff:Giving up api_post(...) after 6 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/challenge/4rwLnEPj/accept)

Then it fails. The problems seems to be sporadic, it does not happen every time. I wonder if there are any fixes for this that address the problem?

Thanks in advance,
with best regards, Volodymyr.

**Comment by fli** [comment]
Are you on version 0.3 or later? This looks like the error that is described in #47 and fixed in v0.3
