### ISSUE TITLE
Auto aborting BOT games

### ISSUE THREAD

**Issue by gbtami** [careless25/lichess-bot#57]
Many spectators looking at https://lichess.org/@/LeelaChess/tv LeelaChess vs TiagoRibeiro3 1+0 rated bullet game right now. BOT played 1. e4 but the human opponent seems to not responding at all and he was disconnected.

BOT games should be aborted if opponent is not responding in given time after BOT first move was taken. Similar to human-human games.

**Comment by lakinwecker** [comment]
Duplicate of #17

**Comment by gbtami** [comment]
Sry I'v missed it.
