### ISSUE TITLE
Auto decline takeback offers

### ISSUE THREAD

**Issue by IntenceYT** [careless25/lichess-bot#60]

**Comment by ddugovic** [comment]
But Lichess has a user preference to decline takebacks?

**Comment by ornicar** [comment]
Indeed, use the preference instead.

**Comment by fathzer** [comment]
Hi,
It seems the when the bot is configured in Lichess preferences to permit takeback, the bot never replies to takeback offers.
I clearly don't speak Python, so, I maybe totally wrong, but looking at lichess-bot.py, it seems the takeback events are ignored. I also had a look at lichess.py, and found nothing to reply to takeback offers.
I also found nothing in config.yml that could be a setting for that.
What did I miss?

**Comment by ddugovic** [comment]
> Hi, It seems that when the bot is configured in Lichess preferences to permit takeback, the bot never replies to takeback offers... What did I miss?

If the feature request is, "Auto decline takeback offers" then don't configure the bot to permit takeback offers... just select "Never".  We don't need additional code to solve this issue:
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/1834123/5f8b78ad-743f-45ff-92b1-7bab7247f238)

**Comment by fathzer** [comment]
> If the feature request is, "Auto decline takeback offers" then don't configure the bot to permit takeback offers... just select "Never". We don't need additional code to solve this issue

Thanks for answering so quickly. Unfortunately, it is not the desired behaviour. What I'm looking for is a way to have the bot accept the incoming takeback requests. I selected the "always" option in the screen you copied. So, the bot receives a takeback offer (because takebacks always require approval), but never replies to it ... so there's no tackback possibility.

**Comment by MarkZH** [comment]
@fathzer You didn't miss anything. Lichess-bot doesn't have the capability to respond to move takeback requests. In its current form, lichess-bot does not listen for incoming messages from lichess while the bot is thinking about its move, so it can't respond to takeback requests. If you want, you can open a new issue to request this feature, though it may take some time to implement.

**Comment by fathzer** [comment]
Thanks a lot, I've just created the #934 feature request.
