### ISSUE TITLE
Uci options don't work

### ISSUE THREAD

**Issue by Aspiration-to-Stars** [careless25/lichess-bot#62]
I tried to change uci options: 

ucioptions:
  Threads: "1"
  Hash: "1024"
  Book File: "engines/book.bin"
  Slow Mover: 10
  Move Overhead: 5000

I tried also 
 Move Overhead: "5000" and "Move Overhead": 5000

I tried to add this in engine_wrapper.py with self.engine.setoption({"Move Overhead": 5000})

and in main.py with engine.send_line("setoption name Move Overhead value 5000")

But speed stays the same in all cases.

I tried different numbers, tried setting it to 0, to 1000. No effect.

**Comment by Aspiration-to-Stars** [comment]
Doesn't work too...

**Comment by mroh69** [comment]
on some engines its called "Overhead" (komodo for example). uci option names have no standard.
To find out the names of you engine:
start your engine in a terminal and type "uci"
you should see for example:
```
option name Contempt type spin default 20 min -100 max 100
option name Analysis Contempt type check default false
option name Threads type spin default 1 min 1 max 512
option name Hash type spin default 16 min 1 max 131072
```
everything between "name" and "type" is the option name you have to use.
(the engines i know, the case doesnt matter, but Im not sure about that)

**Comment by Aspiration-to-Stars** [comment]
I used Stockfish, and I just checked it: it's "Move Overhead". Isn't there a way to set Move Overhead through this terminal? Or tune the engine before it's loaded into the program?

**Comment by gbtami** [comment]
Try to change logging level from INFO to DEBUG at https://github.com/careless25/lichess-bot/blob/master/main.py#L201
This will cause python-chess to send all conversation to the console.

**Comment by Aspiration-to-Stars** [comment]
Also doesn't seem to do anything...

**Comment by careless25** [comment]
So can I close this issue? Do the options work now with the new version?

**Comment by ddugovic** [comment]
@Aspiration-to-Stars Try to change logging level from INFO to DEBUG at https://github.com/careless25/lichess-bot/blob/master/main.py#L201
This will cause python-chess to send all conversation to the console.

Your bot is doing something extraordinarily strange and without a complete log we can only guess how it works.

**Comment by Aspiration-to-Stars** [comment]
Yes, this was solved, thank you. Now only this appear: https://github.com/careless25/lichess-bot/issues/94.
