### ISSUE TITLE
Opening Books for Different Varients

### ISSUE THREAD

**Issue by them492017** [careless25/lichess-bot#75]
Currently, if you use an opening book, it will play the moves for all variants. However, this is undesirable as different variants have different moves played in the opening for example atomic most commonly games begin with 1. Nf3 f6 but in standard if 1. Nf3 is played the most common continuation is 1. ... Nf6 .  Thanks, TheM492017.

**Comment by ddugovic** [comment]
Strange, this is no fault of the Polyglot extended format: http://hgm.nubati.net/book_format.html

**Comment by gbtami** [comment]
I think python-chess does not support Polyglot extended format.

**Comment by careless25** [comment]
so can someone make a ticket on python-chess and ask for extended format?

**Comment by ddugovic** [comment]
Well, it's not quite that simple, either... years ago I tried to fork PolyGlot itself to support variant moves:
https://github.com/ddugovic/polyglot

**Comment by gbtami** [comment]
Some illustrative games:
https://lichess.org/zNholvWl
https://lichess.org/WvqxhbC2

Seems a combined variant book creation and usage is far away so here is my suggestion.
Extend lichess-bot with per variant polyglot book support. Instead of having one `book:"engines/book.bin"` line we should have  standar_book, antichess_book, atomic_book etc lines. What do you think?

**Comment by ddugovic** [comment]
@gbtami PolyGlot doesn't support illegal moves.

**Comment by gbtami** [comment]
@ddugovic agreed, but this doesn't prevent creating and using variant books containing only legal moves. For example AtomicVsEngineBot say as intro chat: "AtomicVsEngine playing from > 2200 rated all time lichess book ( contains more than one million moves )".

**Comment by ddugovic** [comment]
@gbtami Standard polyglot (as opposed to combined/multi-variant which I experimented with) wouldn't support:
1. e4 d5 2. exd5 Qxd2#

**Comment by gbtami** [comment]
@ddugovic I'm not talking here about polyglot as a program, but about polyglot as a (standard, non variant) book format. polyglot (the program) is not the only possibility to create books. As I know Xboard is able to create/edit polyglot books and others are using python scripts like https://gist.github.com/lichapibot/bf1a4916f5eb2e7087f347c834b90a58 or https://github.com/lichapibot/lichess-bot/blob/master/xmlbook.py
