### ISSUE TITLE
Bot cannot be run just by opening "lichess-bot.py" as before

### ISSUE THREAD

**Issue by Aspiration-to-Stars** [careless25/lichess-bot#92]
Before there was a file named main.py, and I could just click it two times, and the bot would be automatically enabled. But now I have to go to PowerShell, then do 
cd "directory"
./.venv/Scripts/activate
python lichess-bot.py
every time. If I don't execute "./.venv/Scripts/activate" before, I get this:

Traceback (most recent call last):
  File "lichess-bot.py", line 8, in <module>
    import lichess
  File "E:\chess\lichess-bot-master\lichess.py", line 14, in <module>
    import backoff
ModuleNotFoundError: No module named 'backoff'
PS E:\chess\lichess-bot-master>

And for "./.venv/Scripts/activate" to be executed, scripts should be allowed on the computer, and this is potentially dangerous for the system.

**Comment by ddugovic** [comment]
Is the `backoff` python module installed by following the steps in the README?

**Comment by Aspiration-to-Stars** [comment]
I did install new requirements.txt (so it should have been installed), but after installing backoff separately it works, thank you!
